//定义基础牌型为ABC,AAB,ABCD,AABC,AABB,ABCDE,AABCD,AABBC,ABCDEF,其策略为基础策略,已穷举//
//suggest类希望把其他牌型化归为基础牌型,从而给出策略//
//基础牌型和其他牌型中都没有顺子和刻子//
//可以证明对同种花色的九种牌,持有的牌的种类大于等于七种牌时,必然会有三张是顺子,从而化归为基础牌型//
//其他牌型内的总牌数大于等于6个时,进行拆分化归，取所有情况的最佳策略//
/*下面给出其他牌型的化归策略:
    AABCDE->VALmin{AAB,CDE;AAC,BDE;AAD,BCE;AAE,BCD;ABC,ADE;ABD,ACE;ABE,ACD}
    AABBCD->VALmin{AAB,BCD;AAC,BBD;AAD,BBC;ABB,ACD;ABD,ABC}
    AABBCC->VALmin{AAB,BCC;AAC,BBC;ABB,ACC;ABC,ABC}
    AABCDEF->VALmin{AAB,CDEF;AAC,BDEF,AAD,BCEF;AAE,BCDF;AAF,BCDE;ABC,ADEF;ABD,ACEF;ABE,ACDF;ABF,ACDE;ACD,ABEF;ACE,ABDF;ACF,ABDE;ADE,ABCF;ADF,ABCE;AEF,ABCD;BCD,AAEF;BCE,AADF;BCF,AADE;BDE,AACF;BDF,AACE;BEF,AACD;CDE,AABF;CEF,AABD;DEF,AABC}
    AABBCDE->VALmin{AAB,BCDE;AAC,BBDE;AAD,BBCE;AAE,BBCD;ABB,ACDE;ABC,ABDE;ABD,ABCE;ABE,ABCD;ACD,ABBE;ACE,ABBD;ADE,ABBC;BBC,AADE;BBD,AACE;BBE,AACE;BCD,AABE;BCE,AABD;BDE,AABC;CDE,AABB}
    AABBCCD->VALmin{AAB,BCCD;AAC,BBCD;AAD,BBCC;ABB,ACCD;ABC,ABCD;ABD,ABCC;ACC,ABDD;ACD,ABBC;BBC,AACD;BBD,AACC;BCC,AABD;BCD,AABC}
    AABBCDEF->VALmin{/}
    AABBCCDE->VALmin{/}
    AABBCCDD->VALmin{/}
    AABBCCDEF->VALmin{/}
    AABBCCDDE->VALmin{/}
    AABBCCDDEF->VALmin{/}
 */
public class suggest {

}
